esMedicina(aspirina).
esPracticaIndigena(herbolaria).
vienenDePlantas(medicinas).
vienenDePlantas(elementos).
vieneDelSauce(aspirina).
planta(sauce).
paisesHerbolaria(mexico).
seUsaEnHerbolaria(plantas).
seUsaEnHerbolaria(elementos).
efectosSecundarios(plantas).
efectosSecundarios(medicinas).
vienenDeNaturaleza(plantas).
curanEnfermedades(medicinas).
curanEnfermedades(plantas).
noTieneAditivos(plantas).
medicosUsan(medicinas).
curanderosUsan(plantas).
VienenDeplantas(clorofila).
estudianLasPlantas(universidades).
estudianLasPlantas(curanderos).
estudianLasPlantas(chamanes).
curanPersonas(doctores).
curanPersonas(curanderos).

